//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineTelegraf.ServiceMorze {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceMorze.IServiceMorze", CallbackContract=typeof(OnlineTelegraf.ServiceMorze.IServiceMorzeCallback))]
    public interface IServiceMorze {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMorze/Connect", ReplyAction="http://tempuri.org/IServiceMorze/ConnectResponse")]
        int Connect(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMorze/Connect", ReplyAction="http://tempuri.org/IServiceMorze/ConnectResponse")]
        System.Threading.Tasks.Task<int> ConnectAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMorze/Disconnect", ReplyAction="http://tempuri.org/IServiceMorze/DisconnectResponse")]
        void Disconnect(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMorze/Disconnect", ReplyAction="http://tempuri.org/IServiceMorze/DisconnectResponse")]
        System.Threading.Tasks.Task DisconnectAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceMorze/SendSignal")]
        void SendSignal(int tick, int senderID);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceMorze/SendSignal")]
        System.Threading.Tasks.Task SendSignalAsync(int tick, int senderID);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceMorze/SendMsg")]
        void SendMsg(string msg, int senderID);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceMorze/SendMsg")]
        System.Threading.Tasks.Task SendMsgAsync(string msg, int senderID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceMorzeCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceMorze/SignalCallback")]
        void SignalCallback(int tick, int senderID);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceMorze/MsgCallback")]
        void MsgCallback(string msg, int senderID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceMorzeChannel : OnlineTelegraf.ServiceMorze.IServiceMorze, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceMorzeClient : System.ServiceModel.DuplexClientBase<OnlineTelegraf.ServiceMorze.IServiceMorze>, OnlineTelegraf.ServiceMorze.IServiceMorze {
        
        public ServiceMorzeClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ServiceMorzeClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ServiceMorzeClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceMorzeClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceMorzeClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public int Connect(string username) {
            return base.Channel.Connect(username);
        }
        
        public System.Threading.Tasks.Task<int> ConnectAsync(string username) {
            return base.Channel.ConnectAsync(username);
        }
        
        public void Disconnect(int id) {
            base.Channel.Disconnect(id);
        }
        
        public System.Threading.Tasks.Task DisconnectAsync(int id) {
            return base.Channel.DisconnectAsync(id);
        }
        
        public void SendSignal(int tick, int senderID) {
            base.Channel.SendSignal(tick, senderID);
        }
        
        public System.Threading.Tasks.Task SendSignalAsync(int tick, int senderID) {
            return base.Channel.SendSignalAsync(tick, senderID);
        }
        
        public void SendMsg(string msg, int senderID) {
            base.Channel.SendMsg(msg, senderID);
        }
        
        public System.Threading.Tasks.Task SendMsgAsync(string msg, int senderID) {
            return base.Channel.SendMsgAsync(msg, senderID);
        }
    }
}
